matrix:
- name: LaTeX
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
  pipeline:
  - pyspelling.filters.pattern:
      pattern: '(?P<text>.*?)(\\[a-zA-Z]+|\$|%)'
      group: text
  sources:
  - '**/*.tex'
  default_encoding: utf-8
