matrix:
- name: LaTeX
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    output: build/dictionary.txt
  pipeline:
  - pyspelling.filters.context:
      context_visible: false
      delimiters:
      - open: '(?s)\\\\[a-zA-Z]+\{'
        close: '\}'
      - open: '\\\\[a-zA-Z]+'
        close: ''
      - open: '%'
        close: '\n'
      - open: '\$'
        close: '\$'
  sources:
  - '**/*.tex'
  default_encoding: utf-8
