---
name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v2.1.1
        with:
          format: 
          filename: article.tex
          options: -shell-escape
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-pdf
          path: article.pdf
      
